cache:
  key: $CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID
  paths:
    - composer.lock
    - vendor/

stages:
  - build
  - lint
  - unit_tests
  - functional_tests
  - phpstan
  - publish_package

build:
  stage: build
  script:
    - curl -sS https://getcomposer.org/installer | php
    - /usr/bin/php7.4 composer.phar install

lint:
  stage: lint
  script:
    - ./vendor/bin/phpcs --standard=PSR2 --ignore=vendor/*,var/*,bin/*,config/* -n . -v

phpstan:
  stage: phpstan
  script:
    - vendor/bin/phpstan analyse

unit_tests:
  stage: unit_tests
  script:
    - /usr/bin/php7.4 ./vendor/bin/simple-phpunit --testsuite unit_tests

functional_tests:
  stage: functional_tests
  script:
    - /usr/bin/php7.4 ./vendor/bin/simple-phpunit --testsuite functional_tests

publish_package:
  image: curlimages/curl:latest
  stage: publish_package
  when: manual
  only:
    - tags
  variables:
    URL: "$CI_SERVER_PROTOCOL://$CI_SERVER_HOST:$CI_SERVER_PORT/api/v4/projects/$CI_PROJECT_ID/packages/composer?job_token=$CI_JOB_TOKEN"
  script:
    - version=$([[ -z "$CI_COMMIT_TAG" ]] && echo "branch=$CI_COMMIT_REF_NAME" || echo "tag=$CI_COMMIT_TAG")
    - insecure=$([ "$CI_SERVER_PROTOCOL" = "http" ] && echo "--insecure" || echo "")
    - response=$(curl -s -w "\n%{http_code}" $insecure --data $version $URL)
    - code=$(echo "$response" | tail -n 1)
    - body=$(echo "$response" | head -n 1)
    # Output state information
    - if [ $code -eq 201 ]; then
      echo "Package created - Code $code - $body";
      else
      echo "Could not create package - Code $code - $body";
      exit 1;
      fi
